### ISSUE TITLE
Error with custom channel

### ISSUE THREAD

**Issue by zakjan** [MODLanguage/antlr4-ruby-runtime#8]
Sending tokens to a custom channel throws an error in Ruby runtime. Are channels supported?

It works in other runtimes. The error disappears and parsing passes, when `channel(2)` is replaced with `skip` in the grammar.

```
echo '# comment\nxxx 1,2,3' | bundle exec ruby ./parse.rb
```

```
Traceback (most recent call last):
	29: from ./parse.rb:18:in `<main>'
	28: from xxx/grammar/TestParser.rb:109:in `start'
	27: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/parser.rb:276:in `enter_rule'
	26: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/common_token_stream.rb:31:in `lt'
	25: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/buffered_token_stream.rb:150:in `lazy_init'
	24: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/buffered_token_stream.rb:154:in `setup'
	23: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/buffered_token_stream.rb:68:in `sync'
	22: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/buffered_token_stream.rb:80:in `fetch'
	21: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer.rb:76:in `next_token'
	20: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer.rb:85:in `next_token_inner'
	19: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer.rb:85:in `loop'
	18: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer.rb:97:in `block in next_token_inner'
	17: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer.rb:97:in `loop'
	16: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer.rb:101:in `block (2 levels) in next_token_inner'
	15: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:63:in `match'
	14: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:102:in `match_atn'
	13: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:123:in `exec_atn'
	12: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:123:in `loop'
	11: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:144:in `block in exec_atn'
	10: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:182:in `compute_target_state'
	 9: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:241:in `reachable_config_set'
	 8: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:339:in `closure'
	 7: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:339:in `closure'
	 6: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:337:in `closure'
	 5: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_atn_simulator.rb:386:in `epsilon_target'
	 4: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_action_executor.rb:13:in `append'
	 3: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_action_executor.rb:13:in `new'
	 2: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_action_executor.rb:9:in `initialize'
	 1: from xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_action_executor.rb:9:in `calculate'
xxx/.bundle/ruby/2.7.0/gems/antlr4-runtime-0.2.10/lib/antlr4/runtime/lexer_channel_action.rb:25:in `hash': undefined method `ordinal' for 0:Integer (NoMethodError)
```

parse.rb

```
require './TestListener'
require './TestBaseListener'
require './TestVisitor'
require './TestLexer'
require './TestParser'

input = STDIN.read

char_stream = Antlr4::Runtime::CharStreams.from_string(input, 'String')
lexer = Test::TestLexer.new(char_stream)
token_stream = Antlr4::Runtime::CommonTokenStream.new(lexer)
parser = Test::TestParser.new(token_stream)
parse_tree = parser.start()
```

Parser is generated by this command:

```
java -jar ~/.m2/repository/org/antlr/antlr4/4.7.3-SNAPSHOT/antlr4-4.7.3-SNAPSHOT-complete.jar \
    -listener \
    -visitor \
    -Dlanguage=Ruby \
    -package Test \
    Test.g4
```

Test.g4

```
grammar Test;

start
    : line+
    ;

line
    : filepath ' ' number (',' number)*
    ;

filepath
    : Filepath
    ;

number
    : Number
    ;

// lexer

Number
    : [0-9]+
    ;

Filepath
    : [a-zA-Z0-9\-_./]+
    ;

LineComment
    : '#' ~[\n]*
    -> channel(2)
    ;

Whitespace
    : [ \t\r\n\u000c]+
    -> skip
    ;
```

**Comment by twalmsley** [comment]
Looks like a bug - I don't use this feature so didn't test it. I will try to find the time to fix the problem, but it is likely to be a few weeks as I'm busy on other work.
